"""竞彩联赛 / 球队名 → ESPN 的桥接映射。

体彩每周开售的联赛并不固定（取决于官方），本模块尽量覆盖竞彩常见的
足球 / 篮球联赛与杯赛，并采用「尽力匹配 + 未匹配透明报告」的策略：

- LEAGUE_MAP：竞彩联赛名（含别名）→ (sport, espn_league_code)。
  sport 取值统一为 DL/爬虫词表 "football" / "basketball"（不要用 "soccer"，
  否则 dl 的 LABEL_MAP 会 KeyError）。ESPN 站点路径的 soccer/basketball
  由爬虫内部另行处理。
- TEAM_ALIASES：俱乐部中文队名（含别名）→ (sport, code, espn_team_name)。
  英文侧使用 ESPN scoreboard 的 displayName（已按各联赛实测校准）。
- NATIONAL_TEAMS：国家队中文名 → ESPN 英文名。国家队会出现在多种赛事
  （世界杯 / 世预赛 / 欧洲杯 / 欧国联 / 美洲杯 / 友谊赛…），因此单列一张
  共享表，凡属 NATIONAL_COMP_CODES 的赛事都用它解析，避免逐赛事重复维护。

所有联赛 code 均已对 ESPN 站点 API 实测有效。未能映射的联赛 / 队名不会
报错，而是随报告一并列出，便于后续往这两张表追加补全。

匹配的容错（重音/标点折叠、子串近似）在 matcher.py 中实现，因此英文侧
即便与 ESPN 当季 displayName 略有出入（如缩写）也能匹配上。
"""
from __future__ import annotations

from typing import Optional

# ---------------------------------------------------------------------------
# 竞彩联赛名（含别名）→ (sport, espn_league_code)
# ---------------------------------------------------------------------------
LEAGUE_MAP: dict[str, tuple[str, str]] = {
    # ===================== 足球 · 欧洲主流联赛 =====================
    "英超": ("football", "eng.1"), "英格兰超级联赛": ("football", "eng.1"),
    "英冠": ("football", "eng.2"), "英格兰冠军联赛": ("football", "eng.2"),
    "英甲": ("football", "eng.3"), "英乙": ("football", "eng.4"),
    "西甲": ("football", "esp.1"), "西班牙甲级联赛": ("football", "esp.1"),
    "西乙": ("football", "esp.2"),
    "意甲": ("football", "ita.1"), "意大利甲级联赛": ("football", "ita.1"),
    "意乙": ("football", "ita.2"),
    "德甲": ("football", "ger.1"), "德国甲级联赛": ("football", "ger.1"),
    "德乙": ("football", "ger.2"),
    "法甲": ("football", "fra.1"), "法国甲级联赛": ("football", "fra.1"),
    "法乙": ("football", "fra.2"),
    "荷甲": ("football", "ned.1"), "荷兰甲级联赛": ("football", "ned.1"),
    "荷乙": ("football", "ned.2"),
    "葡超": ("football", "por.1"), "葡萄牙超级联赛": ("football", "por.1"),
    "苏超": ("football", "sco.1"), "苏格兰超级联赛": ("football", "sco.1"),
    "苏冠": ("football", "sco.2"),
    "土超": ("football", "tur.1"), "土耳其超级联赛": ("football", "tur.1"),
    "土甲": ("football", "tur.2"),
    "俄超": ("football", "rus.1"), "俄罗斯超级联赛": ("football", "rus.1"),
    "比甲": ("football", "bel.1"), "比利时甲级联赛": ("football", "bel.1"),
    "奥甲": ("football", "aut.1"), "奥地利甲级联赛": ("football", "aut.1"),
    "瑞士超": ("football", "sui.1"), "瑞士超级联赛": ("football", "sui.1"),
    "丹超": ("football", "den.1"), "丹麦超级联赛": ("football", "den.1"),
    "瑞典超": ("football", "swe.1"), "瑞典超级联赛": ("football", "swe.1"),
    "挪超": ("football", "nor.1"), "挪威超级联赛": ("football", "nor.1"),
    "希腊超": ("football", "gre.1"), "希腊超级联赛": ("football", "gre.1"),
    "捷克甲": ("football", "cze.1"),
    "罗甲": ("football", "rou.1"),
    "塞浦超": ("football", "cyp.1"),
    "以超": ("football", "isr.1"), "以色列超级联赛": ("football", "isr.1"),
    # ===================== 足球 · 美洲 / 亚洲 / 其他 =====================
    "巴甲": ("football", "bra.1"), "巴西甲级联赛": ("football", "bra.1"),
    "巴乙": ("football", "bra.2"),
    "阿甲": ("football", "arg.1"), "阿根廷甲级联赛": ("football", "arg.1"),
    "阿乙": ("football", "arg.2"),
    "墨超": ("football", "mex.1"), "墨西哥超级联赛": ("football", "mex.1"),
    "哥伦甲": ("football", "col.1"),
    "智甲": ("football", "chi.1"),
    "美职": ("football", "usa.1"), "美职业": ("football", "usa.1"),
    "美国职业大联盟": ("football", "usa.1"), "大联盟": ("football", "usa.1"),
    "美国女足": ("football", "usa.nwsl"),
    "日职": ("football", "jpn.1"), "日职联": ("football", "jpn.1"),
    "日本职业联赛": ("football", "jpn.1"),
    "韩k": ("football", "kor.1"),  # 备注：ESPN 已无该 code，保留仅作报告可读
    "澳超": ("football", "aus.1"), "澳大利亚超级联赛": ("football", "aus.1"),
    "中超": ("football", "chn.1"), "中国超级联赛": ("football", "chn.1"),
    "沙特": ("football", "ksa.1"), "沙特联": ("football", "ksa.1"),
    "沙特超": ("football", "ksa.1"), "沙特职业联赛": ("football", "ksa.1"),
    "印度超": ("football", "ind.1"),
    # ===================== 足球 · 欧洲三大杯 / 洲际俱乐部 =====================
    "欧冠": ("football", "uefa.champions"), "欧洲冠军联赛": ("football", "uefa.champions"),
    "欧联": ("football", "uefa.europa"), "欧联杯": ("football", "uefa.europa"),
    "欧罗巴": ("football", "uefa.europa"), "欧罗巴联赛": ("football", "uefa.europa"),
    "欧会": ("football", "uefa.europa.conf"), "欧协联": ("football", "uefa.europa.conf"),
    "欧洲协会联赛": ("football", "uefa.europa.conf"),
    "欧超杯": ("football", "uefa.super_cup"), "欧洲超级杯": ("football", "uefa.super_cup"),
    "解放者杯": ("football", "conmebol.libertadores"),
    "南美解放者杯": ("football", "conmebol.libertadores"),
    "南美杯": ("football", "conmebol.sudamericana"),
    "亚冠": ("football", "afc.champions"), "亚冠精英": ("football", "afc.champions"),
    "亚洲冠军联赛": ("football", "afc.champions"),
    "中北美冠军杯": ("football", "concacaf.champions"),
    "世俱杯": ("football", "fifa.cwc"), "世界俱乐部杯": ("football", "fifa.cwc"),
    # ===================== 足球 · 国内杯赛 =====================
    "足总杯": ("football", "eng.fa"), "英格兰足总杯": ("football", "eng.fa"),
    "联赛杯": ("football", "eng.league_cup"), "英联赛杯": ("football", "eng.league_cup"),
    "卡拉宝杯": ("football", "eng.league_cup"),
    "德国杯": ("football", "ger.dfb_pokal"),
    "国王杯": ("football", "esp.copa_del_rey"), "西班牙国王杯": ("football", "esp.copa_del_rey"),
    "意大利杯": ("football", "ita.coppa_italia"),
    "法国杯": ("football", "fra.coupe_de_france"),
    # ===================== 足球 · 国家队赛事（用 NATIONAL_TEAMS 解析）=====
    "世界杯": ("football", "fifa.world"), "国际足联世界杯": ("football", "fifa.world"),
    "欧洲杯": ("football", "uefa.euro"), "欧洲国家杯": ("football", "uefa.euro"),
    "欧国联": ("football", "uefa.nations"), "欧洲国家联赛": ("football", "uefa.nations"),
    "欧预赛": ("football", "uefa.euroq"), "欧洲杯预选赛": ("football", "uefa.euroq"),
    "美洲杯": ("football", "conmebol.america"),
    "亚洲杯": ("football", "afc.asian.cup"),
    "非洲杯": ("football", "caf.nations"), "非洲国家杯": ("football", "caf.nations"),
    "中北美国家联赛": ("football", "concacaf.nations.league"),
    "金杯": ("football", "concacaf.gold"), "美洲金杯": ("football", "concacaf.gold"),
    "国际友谊": ("football", "fifa.friendly"), "友谊赛": ("football", "fifa.friendly"),
    "国际友谊赛": ("football", "fifa.friendly"),
    "世预赛欧洲区": ("football", "fifa.worldq.uefa"), "欧洲区世预赛": ("football", "fifa.worldq.uefa"),
    "世预赛南美区": ("football", "fifa.worldq.conmebol"), "南美区世预赛": ("football", "fifa.worldq.conmebol"),
    "世预赛亚洲区": ("football", "fifa.worldq.afc"), "亚洲区世预赛": ("football", "fifa.worldq.afc"),
    "世预赛中北美区": ("football", "fifa.worldq.concacaf"), "中北美区世预赛": ("football", "fifa.worldq.concacaf"),
    "世预赛非洲区": ("football", "fifa.worldq.caf"), "非洲区世预赛": ("football", "fifa.worldq.caf"),
    "世预赛大洋洲区": ("football", "fifa.worldq.ofc"),
    # ===================== 篮球 =====================
    "nba": ("basketball", "nba"), "美职篮": ("basketball", "nba"), "美国男篮职业联赛": ("basketball", "nba"),
    "wnba": ("basketball", "wnba"), "美职女篮": ("basketball", "wnba"), "美国女子篮球联盟": ("basketball", "wnba"),
    "欧篮联": ("basketball", "euroleague"), "欧洲篮球冠军联赛": ("basketball", "euroleague"),
}

# 属于「国家队」性质的赛事 code：这些赛事的参赛方用 NATIONAL_TEAMS 解析。
NATIONAL_COMP_CODES: set[str] = {
    "fifa.world", "uefa.euro", "uefa.nations", "uefa.euroq",
    "conmebol.america", "afc.asian.cup", "caf.nations",
    "concacaf.nations.league", "concacaf.gold", "fifa.friendly",
    "fifa.worldq.uefa", "fifa.worldq.conmebol", "fifa.worldq.afc",
    "fifa.worldq.concacaf", "fifa.worldq.caf", "fifa.worldq.ofc",
}

# ---------------------------------------------------------------------------
# 俱乐部：竞彩中文队名（含别名）→ (sport, code, espn_team_name)
# 英文侧为 ESPN scoreboard displayName（已实测）。
# ---------------------------------------------------------------------------
_TEAM_RAW: list[tuple[str, str, str, str]] = [
    # ===== 英超 eng.1 =====
    ("football", "eng.1", "曼城", "Manchester City"),
    ("football", "eng.1", "阿森纳", "Arsenal"),
    ("football", "eng.1", "利物浦", "Liverpool"),
    ("football", "eng.1", "切尔西", "Chelsea"),
    ("football", "eng.1", "曼联", "Manchester United"),
    ("football", "eng.1", "热刺", "Tottenham Hotspur"),
    ("football", "eng.1", "托特纳姆热刺", "Tottenham Hotspur"),
    ("football", "eng.1", "纽卡斯尔", "Newcastle United"),
    ("football", "eng.1", "纽卡", "Newcastle United"),
    ("football", "eng.1", "阿斯顿维拉", "Aston Villa"),
    ("football", "eng.1", "维拉", "Aston Villa"),
    ("football", "eng.1", "西汉姆", "West Ham United"),
    ("football", "eng.1", "西汉姆联", "West Ham United"),
    ("football", "eng.1", "布莱顿", "Brighton & Hove Albion"),
    ("football", "eng.1", "埃弗顿", "Everton"),
    ("football", "eng.1", "布伦特福德", "Brentford"),
    ("football", "eng.1", "富勒姆", "Fulham"),
    ("football", "eng.1", "水晶宫", "Crystal Palace"),
    ("football", "eng.1", "狼队", "Wolverhampton Wanderers"),
    ("football", "eng.1", "伯恩茅斯", "AFC Bournemouth"),
    ("football", "eng.1", "诺丁汉森林", "Nottingham Forest"),
    ("football", "eng.1", "森林", "Nottingham Forest"),
    ("football", "eng.1", "卢顿", "Luton Town"),
    ("football", "eng.1", "谢菲联", "Sheffield United"),
    ("football", "eng.1", "伯恩利", "Burnley"),
    ("football", "eng.1", "莱斯特城", "Leicester City"),
    ("football", "eng.1", "利兹联", "Leeds United"),
    ("football", "eng.1", "南安普顿", "Southampton"),
    ("football", "eng.1", "伊普斯维奇", "Ipswich Town"),
    ("football", "eng.1", "桑德兰", "Sunderland"),
    # ===== 西甲 esp.1 =====
    ("football", "esp.1", "皇家马德里", "Real Madrid"),
    ("football", "esp.1", "皇马", "Real Madrid"),
    ("football", "esp.1", "巴塞罗那", "Barcelona"),
    ("football", "esp.1", "巴萨", "Barcelona"),
    ("football", "esp.1", "马德里竞技", "Atlético Madrid"),
    ("football", "esp.1", "马竞", "Atlético Madrid"),
    ("football", "esp.1", "塞维利亚", "Sevilla"),
    ("football", "esp.1", "比利亚雷亚尔", "Villarreal"),
    ("football", "esp.1", "瓦伦西亚", "Valencia"),
    ("football", "esp.1", "毕尔巴鄂竞技", "Athletic Club"),
    ("football", "esp.1", "皇家社会", "Real Sociedad"),
    ("football", "esp.1", "赫罗纳", "Girona"),
    ("football", "esp.1", "贝蒂斯", "Real Betis"),
    ("football", "esp.1", "皇家贝蒂斯", "Real Betis"),
    ("football", "esp.1", "奥萨苏纳", "Osasuna"),
    ("football", "esp.1", "塞尔塔", "Celta Vigo"),
    ("football", "esp.1", "赫塔菲", "Getafe"),
    ("football", "esp.1", "西班牙人", "Espanyol"),
    ("football", "esp.1", "马洛卡", "Mallorca"),
    ("football", "esp.1", "阿拉维斯", "Alavés"),
    ("football", "esp.1", "拉斯帕尔马斯", "Las Palmas"),
    ("football", "esp.1", "巴列卡诺", "Rayo Vallecano"),
    ("football", "esp.1", "莱加内斯", "Leganés"),
    ("football", "esp.1", "巴利亚多利德", "Real Valladolid"),
    ("football", "esp.1", "埃尔切", "Elche"),
    ("football", "esp.1", "莱万特", "Levante"),
    # ===== 意甲 ita.1 =====
    ("football", "ita.1", "国际米兰", "Internazionale"),
    ("football", "ita.1", "国米", "Internazionale"),
    ("football", "ita.1", "尤文图斯", "Juventus"),
    ("football", "ita.1", "尤文", "Juventus"),
    ("football", "ita.1", "ac米兰", "AC Milan"),
    ("football", "ita.1", "米兰", "AC Milan"),
    ("football", "ita.1", "那不勒斯", "Napoli"),
    ("football", "ita.1", "罗马", "AS Roma"),
    ("football", "ita.1", "拉齐奥", "Lazio"),
    ("football", "ita.1", "亚特兰大", "Atalanta"),
    ("football", "ita.1", "佛罗伦萨", "Fiorentina"),
    ("football", "ita.1", "博洛尼亚", "Bologna"),
    ("football", "ita.1", "都灵", "Torino"),
    ("football", "ita.1", "蒙扎", "Monza"),
    ("football", "ita.1", "科莫", "Como"),
    ("football", "ita.1", "恩波利", "Empoli"),
    ("football", "ita.1", "热那亚", "Genoa"),
    ("football", "ita.1", "莱切", "Lecce"),
    ("football", "ita.1", "卡利亚里", "Cagliari"),
    ("football", "ita.1", "萨索洛", "Sassuolo"),
    ("football", "ita.1", "维罗纳", "Hellas Verona"),
    ("football", "ita.1", "乌迪内斯", "Udinese"),
    ("football", "ita.1", "帕尔马", "Parma"),
    ("football", "ita.1", "威尼斯", "Venezia"),
    ("football", "ita.1", "弗罗西诺内", "Frosinone"),
    # ===== 德甲 ger.1 =====
    ("football", "ger.1", "拜仁慕尼黑", "Bayern Munich"),
    ("football", "ger.1", "拜仁", "Bayern Munich"),
    ("football", "ger.1", "多特蒙德", "Borussia Dortmund"),
    ("football", "ger.1", "多特", "Borussia Dortmund"),
    ("football", "ger.1", "勒沃库森", "Bayer Leverkusen"),
    ("football", "ger.1", "莱比锡", "RB Leipzig"),
    ("football", "ger.1", "红牛莱比锡", "RB Leipzig"),
    ("football", "ger.1", "柏林联合", "1. FC Union Berlin"),
    ("football", "ger.1", "法兰克福", "Eintracht Frankfurt"),
    ("football", "ger.1", "沃尔夫斯堡", "VfL Wolfsburg"),
    ("football", "ger.1", "门兴格拉德巴赫", "Borussia Mönchengladbach"),
    ("football", "ger.1", "门兴", "Borussia Mönchengladbach"),
    ("football", "ger.1", "弗赖堡", "SC Freiburg"),
    ("football", "ger.1", "美因茨", "Mainz"),
    ("football", "ger.1", "霍芬海姆", "TSG Hoffenheim"),
    ("football", "ger.1", "科隆", "FC Cologne"),
    ("football", "ger.1", "斯图加特", "VfB Stuttgart"),
    ("football", "ger.1", "云达不莱梅", "Werder Bremen"),
    ("football", "ger.1", "不莱梅", "Werder Bremen"),
    ("football", "ger.1", "波鸿", "VfL Bochum"),
    ("football", "ger.1", "奥格斯堡", "FC Augsburg"),
    ("football", "ger.1", "海登海姆", "1. FC Heidenheim 1846"),
    ("football", "ger.1", "汉堡", "Hamburg SV"),
    ("football", "ger.1", "圣保利", "FC St. Pauli"),
    ("football", "ger.1", "霍尔斯泰因基尔", "Holstein Kiel"),
    # ===== 法甲 fra.1 =====
    ("football", "fra.1", "巴黎圣日耳曼", "Paris Saint-Germain"),
    ("football", "fra.1", "大巴黎", "Paris Saint-Germain"),
    ("football", "fra.1", "巴黎", "Paris Saint-Germain"),
    ("football", "fra.1", "马赛", "Marseille"),
    ("football", "fra.1", "摩纳哥", "AS Monaco"),
    ("football", "fra.1", "里昂", "Lyon"),
    ("football", "fra.1", "里尔", "Lille"),
    ("football", "fra.1", "雷恩", "Stade Rennais"),
    ("football", "fra.1", "尼斯", "Nice"),
    ("football", "fra.1", "朗斯", "Lens"),
    ("football", "fra.1", "南特", "Nantes"),
    ("football", "fra.1", "斯特拉斯堡", "Strasbourg"),
    ("football", "fra.1", "布雷斯特", "Brest"),
    ("football", "fra.1", "兰斯", "Reims"),
    ("football", "fra.1", "图卢兹", "Toulouse"),
    ("football", "fra.1", "欧塞尔", "AJ Auxerre"),
    ("football", "fra.1", "勒阿弗尔", "Le Havre AC"),
    ("football", "fra.1", "昂热", "Angers"),
    ("football", "fra.1", "巴黎fc", "Paris FC"),
    ("football", "fra.1", "圣埃蒂安", "Saint-Etienne"),
    ("football", "fra.1", "蒙彼利埃", "Montpellier"),
    # ===== 荷甲 ned.1 =====
    ("football", "ned.1", "阿贾克斯", "Ajax Amsterdam"),
    ("football", "ned.1", "埃因霍温", "PSV Eindhoven"),
    ("football", "ned.1", "psv", "PSV Eindhoven"),
    ("football", "ned.1", "费耶诺德", "Feyenoord Rotterdam"),
    ("football", "ned.1", "阿尔克马尔", "AZ Alkmaar"),
    ("football", "ned.1", "特温特", "FC Twente"),
    ("football", "ned.1", "乌得勒支", "FC Utrecht"),
    ("football", "ned.1", "格罗宁根", "FC Groningen"),
    ("football", "ned.1", "海伦芬", "Heerenveen"),
    ("football", "ned.1", "奈梅亨", "NEC Nijmegen"),
    ("football", "ned.1", "兹沃勒", "PEC Zwolle"),
    ("football", "ned.1", "斯巴达鹿特丹", "Sparta Rotterdam"),
    ("football", "ned.1", "海牙", "ADO Den Haag"),
    ("football", "ned.1", "前进之鹰", "Go Ahead Eagles"),
    ("football", "ned.1", "福图纳锡塔德", "Fortuna Sittard"),
    ("football", "ned.1", "威廉二世", "Willem II"),
    # ===== 葡超 por.1 =====
    ("football", "por.1", "本菲卡", "Benfica"),
    ("football", "por.1", "波尔图", "FC Porto"),
    ("football", "por.1", "里斯本竞技", "Sporting CP"),
    ("football", "por.1", "葡萄牙体育", "Sporting CP"),
    ("football", "por.1", "布拉加", "Braga"),
    ("football", "por.1", "吉马良斯", "Vitória de Guimaraes"),
    ("football", "por.1", "埃斯托里尔", "Estoril"),
    ("football", "por.1", "里奥阿维", "Rio Ave"),
    ("football", "por.1", "法马利康", "FC Famalicao"),
    ("football", "por.1", "阿罗卡", "Arouca"),
    ("football", "por.1", "莫雷伦斯", "Moreirense"),
    ("football", "por.1", "卡萨皮亚", "Casa Pia"),
    ("football", "por.1", "吉尔维森特", "Gil Vicente"),
    ("football", "por.1", "圣克拉拉", "Santa Clara"),
    # ===== 苏超 sco.1 =====
    ("football", "sco.1", "凯尔特人", "Celtic"),
    ("football", "sco.1", "流浪者", "Rangers"),
    ("football", "sco.1", "格拉斯哥流浪者", "Rangers"),
    ("football", "sco.1", "阿伯丁", "Aberdeen"),
    ("football", "sco.1", "哈茨", "Heart of Midlothian"),
    ("football", "sco.1", "赫斯", "Heart of Midlothian"),
    ("football", "sco.1", "希伯尼安", "Hibernian"),
    ("football", "sco.1", "基尔马诺克", "Kilmarnock"),
    ("football", "sco.1", "马瑟韦尔", "Motherwell"),
    ("football", "sco.1", "邓迪", "Dundee"),
    ("football", "sco.1", "邓迪联", "Dundee United"),
    ("football", "sco.1", "圣约翰斯通", "St Johnstone"),
    ("football", "sco.1", "圣米伦", "St Mirren"),
    # ===== 比甲 bel.1 =====
    ("football", "bel.1", "布鲁日", "Club Brugge"),
    ("football", "bel.1", "安德莱赫特", "Anderlecht"),
    ("football", "bel.1", "亨克", "Racing Genk"),
    ("football", "bel.1", "根特", "KAA Gent"),
    ("football", "bel.1", "安特卫普", "Antwerp"),
    ("football", "bel.1", "标准列日", "Standard Liege"),
    ("football", "bel.1", "圣图尔登", "Sint-Truidense"),
    ("football", "bel.1", "圣吉罗斯联合", "Union St.-Gilloise"),
    ("football", "bel.1", "梅赫伦", "KV Mechelen"),
    ("football", "bel.1", "西塞尔布鲁日", "Cercle Brugge KSV"),
    ("football", "bel.1", "沙勒罗瓦", "Royal Charleroi SC"),
    ("football", "bel.1", "科特赖克", "KV Kortrijk"),
    ("football", "bel.1", "韦斯特洛", "KVC Westerlo"),
    ("football", "bel.1", "鲁汶", "OH Leuven"),
    # ===== 土超 tur.1 =====
    ("football", "tur.1", "加拉塔萨雷", "Galatasaray"),
    ("football", "tur.1", "费内巴切", "Fenerbahce"),
    ("football", "tur.1", "贝西克塔斯", "Besiktas"),
    ("football", "tur.1", "特拉布宗体育", "Trabzonspor"),
    ("football", "tur.1", "伊斯坦布尔", "Istanbul Basaksehir"),
    ("football", "tur.1", "萨姆松体育", "Samsunspor"),
    ("football", "tur.1", "科尼亚体育", "Konyaspor"),
    ("football", "tur.1", "里泽体育", "Caykur Rizespor"),
    ("football", "tur.1", "安塔利亚体育", "Antalyaspor"),
    ("football", "tur.1", "阿兰亚体育", "Alanyaspor"),
    ("football", "tur.1", "加济安泰普", "Gaziantep FK"),
    ("football", "tur.1", "卡斯帕萨", "Kasimpasa"),
    ("football", "tur.1", "埃于普体育", "Eyupspor"),
    ("football", "tur.1", "格茨佩", "Goztepe"),
    # ===== 俄超 rus.1 =====
    ("football", "rus.1", "泽尼特", "Zenit St Petersburg"),
    ("football", "rus.1", "圣彼得堡泽尼特", "Zenit St Petersburg"),
    ("football", "rus.1", "莫斯科中央陆军", "CSKA Moscow"),
    ("football", "rus.1", "莫斯科斯巴达", "Spartak Moscow"),
    ("football", "rus.1", "克拉斯诺达尔", "Krasnodar"),
    ("football", "rus.1", "莫斯科火车头", "Lokomotiv Moscow"),
    ("football", "rus.1", "莫斯科迪纳摩", "Dinamo Moscow"),
    ("football", "rus.1", "罗斯托夫", "Rostov"),
    ("football", "rus.1", "喀山红宝石", "Rubin Kazan"),
    ("football", "rus.1", "格罗兹尼", "Akhmat Grozny"),
    ("football", "rus.1", "翼", "Krylia Sovetov"),
    # ===== 沙特 ksa.1 =====
    ("football", "ksa.1", "利雅得新月", "Al Hilal"),
    ("football", "ksa.1", "新月", "Al Hilal"),
    ("football", "ksa.1", "利雅得胜利", "Al Nassr"),
    ("football", "ksa.1", "胜利", "Al Nassr"),
    ("football", "ksa.1", "吉达联合", "Al Ittihad"),
    ("football", "ksa.1", "吉达国民", "Al Ahli"),
    ("football", "ksa.1", "利雅得青年人", "Al Shabab"),
    ("football", "ksa.1", "达曼协作", "Al Ettifaq"),
    ("football", "ksa.1", "卡迪西亚", "Al Qadsiah"),
    ("football", "ksa.1", "泰阿旺", "Al Taawoun"),
    ("football", "ksa.1", "费哈", "Al Fateh"),
    ("football", "ksa.1", "费萨里", "Al Fayha"),
    # ===== 巴甲 bra.1 =====
    ("football", "bra.1", "弗拉门戈", "Flamengo"),
    ("football", "bra.1", "帕尔梅拉斯", "Palmeiras"),
    ("football", "bra.1", "科林蒂安", "Corinthians"),
    ("football", "bra.1", "圣保罗", "São Paulo"),
    ("football", "bra.1", "弗鲁米嫩塞", "Fluminense"),
    ("football", "bra.1", "博塔弗戈", "Botafogo"),
    ("football", "bra.1", "格雷米奥", "Grêmio"),
    ("football", "bra.1", "国际", "Internacional"),
    ("football", "bra.1", "巴西国际", "Internacional"),
    ("football", "bra.1", "米内罗竞技", "Atlético-MG"),
    ("football", "bra.1", "克鲁塞罗", "Cruzeiro"),
    ("football", "bra.1", "桑托斯", "Santos"),
    ("football", "bra.1", "巴伊亚", "Bahia"),
    ("football", "bra.1", "瓦斯科达伽马", "Vasco da Gama"),
    ("football", "bra.1", "红牛布拉甘蒂诺", "Red Bull Bragantino"),
    ("football", "bra.1", "帕拉纳竞技", "Athletico-PR"),
    ("football", "bra.1", "维多利亚", "Vitória"),
    ("football", "bra.1", "米拉索尔", "Mirassol"),
    # ===== 阿甲 arg.1 =====
    ("football", "arg.1", "博卡青年", "Boca Juniors"),
    ("football", "arg.1", "河床", "River Plate"),
    ("football", "arg.1", "竞技", "Racing Club"),
    ("football", "arg.1", "独立", "Independiente"),
    ("football", "arg.1", "圣洛伦索", "San Lorenzo"),
    ("football", "arg.1", "拉普拉塔大学生", "Estudiantes de La Plata"),
    ("football", "arg.1", "贝莱斯", "Vélez Sarsfield"),
    ("football", "arg.1", "罗萨里奥中央", "Rosario Central"),
    ("football", "arg.1", "阿根廷青年人", "Argentinos Juniors"),
    ("football", "arg.1", "拉努斯", "Lanús"),
    ("football", "arg.1", "塔耶雷斯", "Talleres (Córdoba)"),
    ("football", "arg.1", "防守与正义", "Defensa y Justicia"),
    ("football", "arg.1", "班菲尔德", "Banfield"),
    ("football", "arg.1", "乌拉坎", "Huracán"),
    # ===== 墨超 mex.1 =====
    ("football", "mex.1", "美洲", "América"),
    ("football", "mex.1", "瓜达拉哈拉", "Guadalajara"),
    ("football", "mex.1", "芝华士", "Guadalajara"),
    ("football", "mex.1", "蓝十字", "Cruz Azul"),
    ("football", "mex.1", "蒙特雷", "Monterrey"),
    ("football", "mex.1", "老虎", "Tigres UANL"),
    ("football", "mex.1", "普马斯", "Pumas UNAM"),
    ("football", "mex.1", "托卢卡", "Toluca"),
    ("football", "mex.1", "帕丘卡", "Pachuca"),
    ("football", "mex.1", "莱昂", "León"),
    ("football", "mex.1", "桑托斯拉古纳", "Santos"),
    ("football", "mex.1", "蒂华纳", "Tijuana"),
    ("football", "mex.1", "亚特拉斯", "Atlas"),
    ("football", "mex.1", "内卡萨", "Necaxa"),
    # ===== 美职 usa.1（MLS）=====
    ("football", "usa.1", "迈阿密国际", "Inter Miami CF"),
    ("football", "usa.1", "洛杉矶银河", "LA Galaxy"),
    ("football", "usa.1", "洛杉矶fc", "LAFC"),
    ("football", "usa.1", "西雅图海湾人", "Seattle Sounders FC"),
    ("football", "usa.1", "亚特兰大联", "Atlanta United FC"),
    ("football", "usa.1", "辛辛那提", "FC Cincinnati"),
    ("football", "usa.1", "哥伦布机员", "Columbus Crew"),
    ("football", "usa.1", "费城联合", "Philadelphia Union"),
    ("football", "usa.1", "波特兰伐木者", "Portland Timbers"),
    ("football", "usa.1", "纽约城", "New York City FC"),
    ("football", "usa.1", "纽约红牛", "Red Bull New York"),
    ("football", "usa.1", "奥兰多城", "Orlando City SC"),
    ("football", "usa.1", "纳什维尔", "Nashville SC"),
    ("football", "usa.1", "圣迭戈", "San Diego FC"),
    # ===== 日职 jpn.1 =====
    ("football", "jpn.1", "浦和红钻", "Urawa Red Diamonds"),
    ("football", "jpn.1", "川崎前锋", "Kawasaki Frontale"),
    ("football", "jpn.1", "横滨水手", "Yokohama F. Marinos"),
    ("football", "jpn.1", "鹿岛鹿角", "Kashima Antlers"),
    ("football", "jpn.1", "神户胜利船", "Vissel Kobe"),
    ("football", "jpn.1", "大阪钢巴", "Gamba Osaka"),
    ("football", "jpn.1", "大阪樱花", "Cerezo Osaka"),
    ("football", "jpn.1", "名古屋鲸八", "Nagoya Grampus"),
    ("football", "jpn.1", "广岛三箭", "Sanfrecce Hiroshima"),
    ("football", "jpn.1", "柏太阳神", "Kashiwa Reysol"),
    ("football", "jpn.1", "fc东京", "FC Tokyo"),
    ("football", "jpn.1", "京都不死鸟", "Kyoto Sanga"),
    ("football", "jpn.1", "东京绿茵", "Tokyo Verdy 1969"),
    ("football", "jpn.1", "町田泽维亚", "Machida Zelvia"),
    ("football", "jpn.1", "清水心跳", "Shimizu S-Pulse"),
    ("football", "jpn.1", "福冈黄蜂", "Avispa Fukuoka"),
    # ===== 澳超 aus.1 =====
    ("football", "aus.1", "悉尼fc", "Sydney FC"),
    ("football", "aus.1", "墨尔本城", "Melbourne City FC"),
    ("football", "aus.1", "墨尔本胜利", "Melbourne Victory"),
    ("football", "aus.1", "中央海岸水手", "Central Coast Mariners"),
    ("football", "aus.1", "西悉尼流浪者", "Western Sydney Wanderers"),
    ("football", "aus.1", "阿德莱德联", "Adelaide United"),
    ("football", "aus.1", "布里斯班狮吼", "Brisbane Roar"),
    ("football", "aus.1", "珀斯光荣", "Perth Glory"),
    ("football", "aus.1", "惠灵顿凤凰", "Wellington Phoenix FC"),
    ("football", "aus.1", "奥克兰fc", "Auckland FC"),
    # ===== 中超 chn.1 =====
    ("football", "chn.1", "上海海港", "Shanghai Port"),
    ("football", "chn.1", "上海申花", "Shanghai Shenhua"),
    ("football", "chn.1", "山东泰山", "Shandong Taishan"),
    ("football", "chn.1", "北京国安", "Beijing Guoan"),
    ("football", "chn.1", "成都蓉城", "Chengdu Rongcheng"),
    ("football", "chn.1", "浙江", "Zhejiang Professional FC"),
    ("football", "chn.1", "武汉三镇", "Wuhan Three Towns"),
    ("football", "chn.1", "河南", "Henan"),
    ("football", "chn.1", "青岛海牛", "Qingdao Hainiu"),
    ("football", "chn.1", "青岛西海岸", "Qingdao West Coast"),
    ("football", "chn.1", "天津津门虎", "Tianjin Jinmen Tiger"),
    ("football", "chn.1", "长春亚泰", "Changchun Yatai"),
    ("football", "chn.1", "大连英博", "Dalian Yingbo"),
    ("football", "chn.1", "深圳新鹏城", "Shenzhen Xinpengcheng"),
    ("football", "chn.1", "云南玉昆", "Yunnan Yukun"),
    ("football", "chn.1", "辽宁铁人", "Liaoning Tieren"),
    # ===== 瑞士超 sui.1 =====
    ("football", "sui.1", "巴塞尔", "FC Basel"),
    ("football", "sui.1", "年轻人", "Young Boys"),
    ("football", "sui.1", "卢加诺", "FC Lugano"),
    ("football", "sui.1", "塞尔维特", "Servette"),
    ("football", "sui.1", "苏黎世", "FC Zürich"),
    ("football", "sui.1", "卢塞恩", "FC Luzern"),
    ("football", "sui.1", "圣加仑", "St. Gallen"),
    ("football", "sui.1", "锡永", "FC Sion"),
    # ===== 奥甲 aut.1 =====
    ("football", "aut.1", "萨尔茨堡红牛", "RB Salzburg"),
    ("football", "aut.1", "萨尔茨堡", "RB Salzburg"),
    ("football", "aut.1", "维也纳快速", "Rapid Vienna"),
    ("football", "aut.1", "斯图姆格拉茨", "SK Sturm Graz"),
    ("football", "aut.1", "奥地利维也纳", "Austria Vienna"),
    ("football", "aut.1", "林茨", "LASK Linz"),
    ("football", "aut.1", "沃尔夫斯贝格", "Wolfsberger"),
    # ===== 丹超 den.1 =====
    ("football", "den.1", "哥本哈根", "F.C. København"),
    ("football", "den.1", "米迪兰", "FC Midtjylland"),
    ("football", "den.1", "布隆德比", "Brøndby IF"),
    ("football", "den.1", "北西兰", "FC Nordsjælland"),
    ("football", "den.1", "奥胡斯", "AGF"),
    ("football", "den.1", "兰讷斯", "Randers FC"),
    ("football", "den.1", "西尔克堡", "Silkeborg IF"),
    ("football", "den.1", "维堡", "Viborg FF"),
    # ===== 瑞典超 swe.1 =====
    ("football", "swe.1", "马尔默", "Malmö FF"),
    ("football", "swe.1", "哈马比", "Hammarby IF"),
    ("football", "swe.1", "哥德堡", "IFK Göteborg"),
    ("football", "swe.1", "尤尔加登", "Djurgården"),
    ("football", "swe.1", "埃尔夫斯堡", "IF Elfsborg"),
    ("football", "swe.1", "赫根", "BK Häcken"),
    ("football", "swe.1", "aik", "AIK"),
    ("football", "swe.1", "卡尔马", "Kalmar FF"),
    # ===== 挪超 nor.1 =====
    ("football", "nor.1", "博多格林特", "Bodo/Glimt"),
    ("football", "nor.1", "莫尔德", "Molde"),
    ("football", "nor.1", "罗森博格", "Rosenborg"),
    ("football", "nor.1", "布兰", "SK Brann"),
    ("football", "nor.1", "瓦勒伦加", "Vålerenga"),
    ("football", "nor.1", "维京", "Viking FK"),
    ("football", "nor.1", "利勒斯特罗姆", "Lillestrom"),
    ("football", "nor.1", "特罗姆瑟", "Tromso"),
    # ===== 希腊超 gre.1 =====
    ("football", "gre.1", "奥林匹亚科斯", "Olympiacos"),
    ("football", "gre.1", "帕纳辛纳科斯", "Panathinaikos"),
    ("football", "gre.1", "帕奥克", "PAOK Salonika"),
    ("football", "gre.1", "aek雅典", "AEK Athens"),
    ("football", "gre.1", "阿里斯", "Aris"),
    ("football", "gre.1", "沃洛斯", "Volos NFC"),
    # ===== NBA nba（ESPN 全称）=====
    ("basketball", "nba", "湖人", "Los Angeles Lakers"),
    ("basketball", "nba", "洛杉矶湖人", "Los Angeles Lakers"),
    ("basketball", "nba", "凯尔特人", "Boston Celtics"),
    ("basketball", "nba", "波士顿凯尔特人", "Boston Celtics"),
    ("basketball", "nba", "勇士", "Golden State Warriors"),
    ("basketball", "nba", "金州勇士", "Golden State Warriors"),
    ("basketball", "nba", "雄鹿", "Milwaukee Bucks"),
    ("basketball", "nba", "热火", "Miami Heat"),
    ("basketball", "nba", "76人", "Philadelphia 76ers"),
    ("basketball", "nba", "费城76人", "Philadelphia 76ers"),
    ("basketball", "nba", "掘金", "Denver Nuggets"),
    ("basketball", "nba", "太阳", "Phoenix Suns"),
    ("basketball", "nba", "菲尼克斯太阳", "Phoenix Suns"),
    ("basketball", "nba", "快船", "LA Clippers"),
    ("basketball", "nba", "洛杉矶快船", "LA Clippers"),
    ("basketball", "nba", "独行侠", "Dallas Mavericks"),
    ("basketball", "nba", "小牛", "Dallas Mavericks"),
    ("basketball", "nba", "森林狼", "Minnesota Timberwolves"),
    ("basketball", "nba", "雷霆", "Oklahoma City Thunder"),
    ("basketball", "nba", "骑士", "Cleveland Cavaliers"),
    ("basketball", "nba", "尼克斯", "New York Knicks"),
    ("basketball", "nba", "灰熊", "Memphis Grizzlies"),
    ("basketball", "nba", "国王", "Sacramento Kings"),
    ("basketball", "nba", "老鹰", "Atlanta Hawks"),
    ("basketball", "nba", "公牛", "Chicago Bulls"),
    ("basketball", "nba", "火箭", "Houston Rockets"),
    ("basketball", "nba", "马刺", "San Antonio Spurs"),
    ("basketball", "nba", "鹈鹕", "New Orleans Pelicans"),
    ("basketball", "nba", "开拓者", "Portland Trail Blazers"),
    ("basketball", "nba", "爵士", "Utah Jazz"),
    ("basketball", "nba", "活塞", "Detroit Pistons"),
    ("basketball", "nba", "步行者", "Indiana Pacers"),
    ("basketball", "nba", "猛龙", "Toronto Raptors"),
    ("basketball", "nba", "魔术", "Orlando Magic"),
    ("basketball", "nba", "奇才", "Washington Wizards"),
    ("basketball", "nba", "黄蜂", "Charlotte Hornets"),
    ("basketball", "nba", "篮网", "Brooklyn Nets"),
    # ===== WNBA wnba =====
    ("basketball", "wnba", "康涅狄格太阳", "Connecticut Sun"),
    ("basketball", "wnba", "拉斯维加斯王牌", "Las Vegas Aces"),
    ("basketball", "wnba", "西雅图风暴", "Seattle Storm"),
    ("basketball", "wnba", "纽约自由", "New York Liberty"),
    ("basketball", "wnba", "芝加哥天空", "Chicago Sky"),
    ("basketball", "wnba", "明尼苏达山猫", "Minnesota Lynx"),
    ("basketball", "wnba", "菲尼克斯水星", "Phoenix Mercury"),
    ("basketball", "wnba", "洛杉矶火花", "Los Angeles Sparks"),
    ("basketball", "wnba", "达拉斯飞翼", "Dallas Wings"),
    ("basketball", "wnba", "华盛顿神秘", "Washington Mystics"),
    ("basketball", "wnba", "印第安纳狂热", "Indiana Fever"),
    ("basketball", "wnba", "亚特兰大梦想", "Atlanta Dream"),
    ("basketball", "wnba", "金州女武神", "Golden State Valkyries"),
]

# ---------------------------------------------------------------------------
# 国家队：中文名 → ESPN 英文名（用于所有 NATIONAL_COMP_CODES 赛事）
# ---------------------------------------------------------------------------
_NATIONAL_RAW: list[tuple[str, str]] = [
    # 欧洲
    ("法国", "France"), ("西班牙", "Spain"), ("英格兰", "England"),
    ("德国", "Germany"), ("意大利", "Italy"), ("葡萄牙", "Portugal"),
    ("荷兰", "Netherlands"), ("比利时", "Belgium"), ("克罗地亚", "Croatia"),
    ("瑞士", "Switzerland"), ("奥地利", "Austria"), ("丹麦", "Denmark"),
    ("瑞典", "Sweden"), ("挪威", "Norway"), ("波兰", "Poland"),
    ("乌克兰", "Ukraine"), ("捷克", "Czechia"), ("塞尔维亚", "Serbia"),
    ("土耳其", "Turkey"), ("希腊", "Greece"), ("苏格兰", "Scotland"),
    ("威尔士", "Wales"), ("爱尔兰", "Republic of Ireland"),
    ("匈牙利", "Hungary"), ("罗马尼亚", "Romania"), ("俄罗斯", "Russia"),
    ("斯洛伐克", "Slovakia"), ("斯洛文尼亚", "Slovenia"),
    ("冰岛", "Iceland"), ("芬兰", "Finland"), ("北马其顿", "North Macedonia"),
    ("阿尔巴尼亚", "Albania"), ("格鲁吉亚", "Georgia"),
    # 南美
    ("巴西", "Brazil"), ("阿根廷", "Argentina"), ("乌拉圭", "Uruguay"),
    ("哥伦比亚", "Colombia"), ("智利", "Chile"), ("秘鲁", "Peru"),
    ("厄瓜多尔", "Ecuador"), ("巴拉圭", "Paraguay"),
    ("委内瑞拉", "Venezuela"), ("玻利维亚", "Bolivia"),
    # 中北美
    ("墨西哥", "Mexico"), ("美国", "United States"), ("加拿大", "Canada"),
    ("哥斯达黎加", "Costa Rica"), ("巴拿马", "Panama"), ("牙买加", "Jamaica"),
    ("洪都拉斯", "Honduras"),
    # 亚洲
    ("日本", "Japan"), ("韩国", "South Korea"), ("澳大利亚", "Australia"),
    ("沙特阿拉伯", "Saudi Arabia"), ("伊朗", "Iran"), ("卡塔尔", "Qatar"),
    ("伊拉克", "Iraq"), ("阿联酋", "United Arab Emirates"),
    ("中国", "China PR"), ("中国国家队", "China PR"),
    ("乌兹别克斯坦", "Uzbekistan"), ("约旦", "Jordan"),
    # 非洲
    ("摩洛哥", "Morocco"), ("塞内加尔", "Senegal"), ("埃及", "Egypt"),
    ("尼日利亚", "Nigeria"), ("加纳", "Ghana"), ("喀麦隆", "Cameroon"),
    ("科特迪瓦", "Ivory Coast"), ("阿尔及利亚", "Algeria"),
    ("突尼斯", "Tunisia"), ("南非", "South Africa"), ("马里", "Mali"),
]


def _norm(s: str) -> str:
    return (s or "").replace(" ", "").replace("　", "").lower()


# 嵌套映射：TEAM_ALIASES[(sport, code)][norm_zh] = espn_team_name
TEAM_ALIASES: dict[tuple[str, str], dict[str, str]] = {}
for _sport, _code, _zh, _espn in _TEAM_RAW:
    TEAM_ALIASES.setdefault((_sport, _code), {})[_norm(_zh)] = _espn

# 国家队共享表：NATIONAL_TEAMS[norm_zh] = espn_country_name
NATIONAL_TEAMS: dict[str, str] = {_norm(zh): en for zh, en in _NATIONAL_RAW}


def resolve_league(name_or_code: str) -> Optional[tuple[str, str]]:
    """竞彩联赛名/编码 → (sport, espn_league_code)。"""
    return LEAGUE_MAP.get(_norm(name_or_code))


def resolve_team(sport: str, code: str, zh_name: str) -> Optional[str]:
    """竞彩中文队名 → ESPN 队名。

    俱乐部走 TEAM_ALIASES；国家队赛事（code ∈ NATIONAL_COMP_CODES）走共享的
    NATIONAL_TEAMS 表，避免为每种国家队赛事重复维护球队名。
    """
    key = _norm(zh_name)
    club = TEAM_ALIASES.get((sport, code), {}).get(key)
    if club:
        return club
    if code in NATIONAL_COMP_CODES:
        return NATIONAL_TEAMS.get(key)
    return None
